version: '3'
services:
  web:
    build:
      context: .
      args:
        PUBLISHABLE_KEY: ${PUBLISHABLE_KEY}  # Set build arg for PUBLISHABLE_KEY
        SECRET_KEY: ${SECRET_KEY}  # Set build arg for SECRET_KEY
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:  # Define environment variables for the web service
      PUBLISHABLE_KEY: ${PUBLISHABLE_KEY}  # Set environment variable for PUBLISHABLE_KEY
      SECRET_KEY: ${SECRET_KEY}  # Set environment variable for SECRET_KEY
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
